"""initial migration

Revision ID: 50b73fd13529
Revises: 
Create Date: 2018-01-19 19:45:40.609764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50b73fd13529'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.create_index(op.f('ix_AdminUser_username'), 'AdminUser', ['username'], unique=True)
    #op.drop_index('ix_AdminUser_username', table_name='AdminUser')
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_AdminUser_username', 'AdminUser', ['username'], unique=True)
    op.drop_index(op.f('ix_AdminUser_username'), table_name='AdminUser')
    # ### end Alembic commands ###
